### ISSUE TITLE
User Story #1

### ISSUE THREAD

**Issue by sjochen** [sjochen/Discover-live-music#3]
As a user I want to be able to search for events.

# Tasks 1.1
- [x] index.html will have a text box
- [x] index.html will have a submit button
- [x] app.js will take the search terms and turn it into a variable
- [x] app.js will take the variables created and make an SeatGeek API call.
